data:
  num_sparse_features:
  dense_features: 
  experiment_group:
  train: 
  test: 

training:
  batch_size: 64
  lr: 0.001
  epochs: 10
  device: "mps"

models:
  mf:
    latent_dim: 16
  neumf:
    latent_dim: 16
    hidden_layers: [32, 32, 32]
  fm:
    latent_dim: 16
  wd:
    latent_dim: 16
    hidden_layers: [32, 32, 32]
    cross_features:
      - ["gender", "genre"]
      - ["gender", "occupation"]
  deepfm:
    latent_dim: 16
    hidden_layers: [32, 32, 32]
  dcn:
    latent_dim: 16
    hidden_layers: [32, 32, 32]
    num_cross_layers: 3

  